import type { Metadata } from "next";
import Sidebar from "../components/DocsComponent/Sidebar";

export const metadata: Metadata = {
  title: "Neuctra UI - A modern UI library with modern designs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-zinc-950 min-h-screen text-white flex">
        <Sidebar />
        <main className="flex-1 max-sm:pt-18 p-4 ml-64">{children}</main>
      </body>
    </html>
  );
}
