import type { Metadata } from "next";
import Sidebar from "../components/docs/Sidebar";

export const metadata: Metadata = {
  title: "Neuctra UI - A modern UI library with modern designs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-zinc-950 w-full min-h-screen text-white">
      {/* Sidebar is fixed, so no flex container needed */}
      <Sidebar />

      {/* Main content with left margin = sidebar width */}
      <main className="ml-64 max-sm:ml-0 max-sm:pt-14 max-lg:px-5 px-4">{children}</main>
    </div>
  );
}
